Be sure to run a Python 3 Jupyter kernel !!!

In [1]:
import numpy as np
from richardson_lucy_deconvolution import *
from lib import utils
from PIL import Image
from os.path import join
source_path = "img"
dest_path = "img/richardson-lucy-deconvolution"

In [2]:
picture = "153412.jpg"
with Image.open(join(source_path, picture)) as pic:

    mask = [3228, 3228+256, 1484, 1484+256]
    u, psf = deblur_module(pic, picture + "-blind-v11-best-2", dest_path, "auto", 5, 15000, 0,
                  mask=mask,
                  refine=True,
                  refine_quality=1,
                  preview=0.5,
                  auto_quality=0.25,
                  method="best",
                  debug=True)



Working on a scaled picture
Padded vertically
Padded horizontally

===== BLIND ESTIMATION OF BLUR =====
[1] [3] [15000]
3
== Pyramid step 1 ==
working on image : (1617, 2437, 3)
15000 0.000584935113663 1
15000 0.000615972805476 1
15000 0.000527651868336 1
15765.1507515 0.000533867246559 1
15765.1507515 0.000563108998786 1
15765.1507515 0.000479562923402 1
10 iterations
10 iterations
10 iterations
[[[ 0.11056158  0.11055694  0.110567  ]
  [ 0.11071553  0.11062933  0.11066854]
  [ 0.11057249  0.11054955  0.11056782]]

 [[ 0.11196245  0.11207571  0.11201478]
  [ 0.11237529  0.1123764   0.11236303]
  [ 0.11196308  0.11207631  0.11201545]]

 [[ 0.11057232  0.11054948  0.1105677 ]
  [ 0.11071549  0.11062927  0.11066849]
  [ 0.11056178  0.11055701  0.11056718]]]

===== BLIND MASKED REFINEMENT =====
working on image : (1617, 2437, 3)
15000 0.00058986243383 1
15000 0.000620708429301 1
15000 0.000532197115422 1


ValueError: operands could not be broadcast together with shapes (4,128) (3,128) (4,128) 